// Code generated by protoc-gen-go.
// source: service1.proto
// DO NOT EDIT!

/*
Package service1 is a generated protocol buffer package.

It is generated from these files:
	service1.proto

It has these top-level messages:
	SensorReadingRep
	SensorReadingsReq
*/
package service1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SensorReadingRep struct {
	Readings string `protobuf:"bytes,1,opt,name=readings" json:"readings,omitempty"`
}

func (m *SensorReadingRep) Reset()                    { *m = SensorReadingRep{} }
func (m *SensorReadingRep) String() string            { return proto.CompactTextString(m) }
func (*SensorReadingRep) ProtoMessage()               {}
func (*SensorReadingRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SensorReadingsReq struct {
	Sensorno string `protobuf:"bytes,1,opt,name=sensorno" json:"sensorno,omitempty"`
}

func (m *SensorReadingsReq) Reset()                    { *m = SensorReadingsReq{} }
func (m *SensorReadingsReq) String() string            { return proto.CompactTextString(m) }
func (*SensorReadingsReq) ProtoMessage()               {}
func (*SensorReadingsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SensorReadingRep)(nil), "service1.SensorReadingRep")
	proto.RegisterType((*SensorReadingsReq)(nil), "service1.SensorReadingsReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Sensor service

type SensorClient interface {
	SendReadings(ctx context.Context, in *SensorReadingsReq, opts ...grpc.CallOption) (*SensorReadingRep, error)
}

type sensorClient struct {
	cc *grpc.ClientConn
}

func NewSensorClient(cc *grpc.ClientConn) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) SendReadings(ctx context.Context, in *SensorReadingsReq, opts ...grpc.CallOption) (*SensorReadingRep, error) {
	out := new(SensorReadingRep)
	err := grpc.Invoke(ctx, "/service1.Sensor/SendReadings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sensor service

type SensorServer interface {
	SendReadings(context.Context, *SensorReadingsReq) (*SensorReadingRep, error)
}

func RegisterSensorServer(s *grpc.Server, srv SensorServer) {
	s.RegisterService(&_Sensor_serviceDesc, srv)
}

func _Sensor_SendReadings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorReadingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).SendReadings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service1.Sensor/SendReadings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).SendReadings(ctx, req.(*SensorReadingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sensor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service1.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReadings",
			Handler:    _Sensor_SendReadings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x35, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xf4,
	0xb8, 0x04, 0x82, 0x53, 0xf3, 0x8a, 0xf3, 0x8b, 0x82, 0x52, 0x13, 0x53, 0x32, 0xf3, 0xd2, 0x83,
	0x52, 0x0b, 0x84, 0xa4, 0xb8, 0x38, 0x8a, 0x20, 0xbc, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x38, 0x5f, 0x49, 0x9f, 0x4b, 0x10, 0x45, 0x7d, 0x71, 0x50, 0x6a, 0x21, 0x48, 0x43, 0x31,
	0x58, 0x30, 0x2f, 0x1f, 0xa6, 0x01, 0xc6, 0x37, 0x0a, 0xe6, 0x62, 0x83, 0x68, 0x10, 0xf2, 0xe4,
	0xe2, 0x01, 0xb2, 0x52, 0x60, 0x1a, 0x85, 0xa4, 0xf5, 0xe0, 0xae, 0xc2, 0x30, 0x52, 0x4a, 0x0a,
	0x87, 0x24, 0xd0, 0x7d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x6f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x38, 0xad, 0x1b, 0x54, 0xd8, 0x00, 0x00, 0x00,
}
